// @ts-nocheck
import * as React from "react"

export type Bank = {
    [name: string]: {
        name: string,
        component: React.LazyExoticComponent<any>
        files: string[]
    }
}

export const Bank: Bank = {
    "button": {
        name: "Button",
        component: React.lazy(() => import("@/workshop/button/button")),
        family: [],
        files: ["src/workshop/button/button.tsx", "src/workshop/button/close-button.tsx", "src/workshop/button/icon-button.tsx",
            "src/workshop/button/index.tsx"],
    },
    "close-button": {
        name: "Close Button",
        component: React.lazy(() => import("@/workshop/button/close-button")),
        family: [],
        files: ["src/workshop/button/button.tsx", "src/workshop/button/close-button.tsx", "src/workshop/button/icon-button.tsx",
            "src/workshop/button/index.tsx"],
    },
    "icon-button": {
        name: "Icon Button",
        component: React.lazy(() => import("@/workshop/button/icon-button")),
        family: [],
        files: ["src/workshop/button/button.tsx", "src/workshop/button/close-button.tsx", "src/workshop/button/icon-button.tsx",
            "src/workshop/button/index.tsx"],
    },
    "checkbox": {
        name: "Checkbox",
        component: React.lazy(() => import("@/workshop/checkbox/checkbox")),
        family: ["basic-field", "input"],
        files: ["src/workshop/checkbox/checkbox-group.tsx", "src/workshop/checkbox/checkbox.tsx", "src/workshop/checkbox/index.tsx"],
    },
    "checkbox-group": {
        name: "CheckboxGroup",
        component: React.lazy(() => import("@/workshop/checkbox/checkbox-group")),
        family: ["basic-field", "input"],
        files: ["src/workshop/checkbox/checkbox-group.tsx", "src/workshop/checkbox/checkbox.tsx", "src/workshop/checkbox/index.tsx"],
    },
    "bar-chart": {
        name: "BarChart",
        component: React.lazy(() => import("@/workshop/charts/bar-chart")),
        family: [],
        files: ["src/workshop/charts/area-chart.tsx", "src/workshop/charts/bar-chart.tsx", "src/workshop/charts/chart-legend.tsx",
            "src/workshop/charts/chart-tooltip.tsx", "src/workshop/charts/color-theme.ts", "src/workshop/charts/donut-chart.tsx",
            "src/workshop/charts/index.tsx", "src/workshop/charts/legend.tsx", "src/workshop/charts/line-chart.tsx", "src/workshop/charts/types.ts",
            "src/workshop/charts/utils.ts"],
    },
    "line-chart": {
        name: "LineChart",
        component: React.lazy(() => import("@/workshop/charts/line-chart")),
        family: [],
        files: ["src/workshop/charts/area-chart.tsx", "src/workshop/charts/bar-chart.tsx", "src/workshop/charts/chart-legend.tsx",
            "src/workshop/charts/chart-tooltip.tsx", "src/workshop/charts/color-theme.ts", "src/workshop/charts/donut-chart.tsx",
            "src/workshop/charts/index.tsx", "src/workshop/charts/legend.tsx", "src/workshop/charts/line-chart.tsx", "src/workshop/charts/types.ts",
            "src/workshop/charts/utils.ts"],
    },
    "area-chart": {
        name: "AreaChart",
        component: React.lazy(() => import("@/workshop/charts/area-chart")),
        family: [],
        files: ["src/workshop/charts/area-chart.tsx", "src/workshop/charts/bar-chart.tsx", "src/workshop/charts/chart-legend.tsx",
            "src/workshop/charts/chart-tooltip.tsx", "src/workshop/charts/color-theme.ts", "src/workshop/charts/donut-chart.tsx",
            "src/workshop/charts/index.tsx", "src/workshop/charts/legend.tsx", "src/workshop/charts/line-chart.tsx", "src/workshop/charts/types.ts",
            "src/workshop/charts/utils.ts"],
    },
    "donut-chart": {
        name: "DonutChart",
        component: React.lazy(() => import("@/workshop/charts/donut-chart")),
        family: [],
        files: ["src/workshop/charts/area-chart.tsx", "src/workshop/charts/bar-chart.tsx", "src/workshop/charts/chart-legend.tsx",
            "src/workshop/charts/chart-tooltip.tsx", "src/workshop/charts/color-theme.ts", "src/workshop/charts/donut-chart.tsx",
            "src/workshop/charts/index.tsx", "src/workshop/charts/legend.tsx", "src/workshop/charts/line-chart.tsx", "src/workshop/charts/types.ts",
            "src/workshop/charts/utils.ts"],
    },
    "loading-spinner": {
        name: "Loading Spinner",
        component: React.lazy(() => import("@/workshop/loading-spinner/loading-spinner")),
        family: [],
        files: ["src/workshop/loading-spinner/index.tsx", "src/workshop/loading-spinner/loading-overlay.tsx",
            "src/workshop/loading-spinner/loading-spinner.tsx"],
    },
    "loading-overlay": {
        name: "Loading Overlay",
        component: React.lazy(() => import("@/workshop/loading-spinner/loading-overlay")),
        family: [],
        files: ["src/workshop/loading-spinner/index.tsx", "src/workshop/loading-spinner/loading-overlay.tsx",
            "src/workshop/loading-spinner/loading-spinner.tsx"],
    },
    "accordion": {
        name: "Accordion",
        component: React.lazy(() => import("@/workshop/accordion/accordion")),
        family: [],
        files: ["src/workshop/accordion/accordion.tsx", "src/workshop/accordion/index.tsx"],
    },
    "address-input": {
        name: "AddressInput",
        component: React.lazy(() => import("@/workshop/address-input/address-input")),
        family: ["autocomplete"],
        files: ["src/workshop/address-input/address-input.tsx", "src/workshop/address-input/index.tsx",
            "src/workshop/address-input/use-address-autocomplete.ts"],
    },
    "alert": {
        name: "Alert",
        component: React.lazy(() => import("@/workshop/alert/alert")),
        family: [],
        files: ["src/workshop/alert/alert.tsx", "src/workshop/alert/index.tsx"],
    },
    "app-layout": {
        name: "AppLayout",
        component: React.lazy(() => import("@/workshop/app-layout/app-layout")),
        family: ["drawer"],
        files: ["src/workshop/app-layout/app-layout.tsx", "src/workshop/app-layout/app-sidebar.tsx", "src/workshop/app-layout/index.tsx"],
    },
    "autocomplete": {
        name: "Autocomplete",
        component: React.lazy(() => import("@/workshop/autocomplete/autocomplete")),
        family: ["basic-field", "command", "input", "popover"],
        files: ["src/workshop/autocomplete/autocomplete.tsx", "src/workshop/autocomplete/index.tsx"],
    },
    "avatar": {
        name: "Avatar",
        component: React.lazy(() => import("@/workshop/avatar/avatar")),
        family: [],
        files: ["src/workshop/avatar/avatar.tsx", "src/workshop/avatar/index.tsx"],
    },
    "badge": {
        name: "Badge",
        component: React.lazy(() => import("@/workshop/badge/badge")),
        family: [],
        files: ["src/workshop/badge/badge.tsx", "src/workshop/badge/index.tsx"],
    },
    "breadcrumbs": {
        name: "Breadcrumbs",
        component: React.lazy(() => import("@/workshop/breadcrumbs/breadcrumbs")),
        family: [],
        files: ["src/workshop/breadcrumbs/breadcrumbs.tsx", "src/workshop/breadcrumbs/index.tsx"],
    },
    "calendar": {
        name: "Calendar",
        component: React.lazy(() => import("@/workshop/calendar/calendar")),
        family: ["button"],
        files: ["src/workshop/calendar/calendar.tsx", "src/workshop/calendar/index.tsx"],
    },
    "card": {
        name: "Card",
        component: React.lazy(() => import("@/workshop/card/card")),
        family: [],
        files: ["src/workshop/card/card.tsx", "src/workshop/card/index.tsx"],
    },
    "carousel": {
        name: "Carousel",
        component: React.lazy(() => import("@/workshop/carousel/carousel")),
        family: ["button"],
        files: ["src/workshop/carousel/carousel.tsx", "src/workshop/carousel/index.tsx"],
    },
    "collapsible": {
        name: "Collapsible",
        component: React.lazy(() => import("@/workshop/collapsible/collapsible")),
        family: [],
        files: ["src/workshop/collapsible/collapsible.tsx", "src/workshop/collapsible/index.tsx"],
    },
    "combobox": {
        name: "Combobox",
        component: React.lazy(() => import("@/workshop/combobox/combobox")),
        family: ["basic-field", "command", "input", "popover"],
        files: ["src/workshop/combobox/combobox.tsx", "src/workshop/combobox/index.tsx"],
    },
    "command": {
        name: "Command",
        component: React.lazy(() => import("@/workshop/command/command")),
        family: ["input"],
        files: ["src/workshop/command/command.tsx", "src/workshop/command/index.tsx"],
    },
    "currency-input": {
        name: "CurrencyInput",
        component: React.lazy(() => import("@/workshop/currency-input/currency-input")),
        family: ["basic-field", "input"],
        files: ["src/workshop/currency-input/currency-input.tsx", "src/workshop/currency-input/index.tsx"],
    },
    "datagrid": {
        name: "Datagrid",
        component: React.lazy(() => import("@/workshop/datagrid/datagrid")),
        family: ["button", "checkbox", "date-picker", "dropdown-menu", "radio-group", "select", "card", "loading-spinner", "number-input",
            "pagination", "skeleton", "text-input", "tooltip"],
        files: ["src/workshop/datagrid/datagrid-cell-input-field.tsx", "src/workshop/datagrid/datagrid-filter.tsx",
            "src/workshop/datagrid/datagrid-instance.tsx", "src/workshop/datagrid/datagrid.tsx", "src/workshop/datagrid/helpers.ts",
            "src/workshop/datagrid/index.tsx", "src/workshop/datagrid/locales.ts", "src/workshop/datagrid/use-datagrid-editing.ts",
            "src/workshop/datagrid/use-datagrid-filtering.ts", "src/workshop/datagrid/use-datagrid-responsiveness.ts",
            "src/workshop/datagrid/use-datagrid-row-selection.ts", "src/workshop/datagrid/use-datagrid-size.ts"],
    },
    "date-picker": {
        name: "DatePicker",
        component: React.lazy(() => import("@/workshop/date-picker/date-picker")),
        family: ["basic-field", "calendar", "input", "modal", "popover", "select"],
        files: ["src/workshop/date-picker/date-picker.tsx", "src/workshop/date-picker/date-range-picker.tsx", "src/workshop/date-picker/index.tsx"],
    },
    "disclosure": {
        name: "Disclosure",
        component: React.lazy(() => import("@/workshop/disclosure/disclosure")),
        family: [],
        files: ["src/workshop/disclosure/disclosure.tsx", "src/workshop/disclosure/index.tsx"],
    },
    "drawer": {
        name: "Drawer",
        component: React.lazy(() => import("@/workshop/drawer/drawer")),
        family: ["button"],
        files: ["src/workshop/drawer/drawer.tsx", "src/workshop/drawer/index.tsx"],
    },
    "dropdown-menu": {
        name: "DropdownMenu",
        component: React.lazy(() => import("@/workshop/dropdown-menu/dropdown-menu")),
        family: [],
        files: ["src/workshop/dropdown-menu/dropdown-menu.tsx", "src/workshop/dropdown-menu/index.tsx"],
    },
    "form": {
        name: "Form",
        component: React.lazy(() => import("@/workshop/form/form")),
        family: ["button", "loading-spinner", "modal", "address-input", "autocomplete", "basic-field", "checkbox", "combobox", "currency-input",
            "date-picker", "simple-dropzone", "native-select", "number-input", "phone-input", "radio-group", "select", "switch", "text-input",
            "textarea"],
        files: ["src/workshop/form/danger-zone.tsx", "src/workshop/form/define-schema.ts", "src/workshop/form/fields.tsx",
            "src/workshop/form/form.tsx", "src/workshop/form/index.tsx", "src/workshop/form/locales.json",
            "src/workshop/form/polymorphic-component.ts", "src/workshop/form/schema-presets.ts", "src/workshop/form/submit-field.tsx",
            "src/workshop/form/zod-resolver.ts"],
    },
    "horizontal-draggable-scroll": {
        name: "HorizontalDraggableScroll",
        component: React.lazy(() => import("@/workshop/horizontal-draggable-scroll/horizontal-draggable-scroll")),
        family: [],
        files: ["src/workshop/horizontal-draggable-scroll/horizontal-draggable-scroll.tsx", "src/workshop/horizontal-draggable-scroll/index.tsx",
            "src/workshop/horizontal-draggable-scroll/use-draggable-scroll.ts"],
    },
    "hover-card": {
        name: "HoverCard",
        component: React.lazy(() => import("@/workshop/hover-card/hover-card")),
        family: [],
        files: ["src/workshop/hover-card/hover-card.tsx", "src/workshop/hover-card/index.tsx"],
    },
    "modal": {
        name: "Modal",
        component: React.lazy(() => import("@/workshop/modal/modal")),
        family: ["button"],
        files: ["src/workshop/modal/index.tsx", "src/workshop/modal/modal.tsx"],
    },
    "native-select": {
        name: "NativeSelect",
        component: React.lazy(() => import("@/workshop/native-select/native-select")),
        family: ["basic-field", "input"],
        files: ["src/workshop/native-select/index.tsx", "src/workshop/native-select/native-select.tsx"],
    },
    "navigation-menu": {
        name: "NavigationMenu",
        component: React.lazy(() => import("@/workshop/navigation-menu/navigation-menu")),
        family: ["drawer", "vertical-menu"],
        files: ["src/workshop/navigation-menu/index.tsx", "src/workshop/navigation-menu/navigation-menu.tsx"],
    },
    "number-input": {
        name: "NumberInput",
        component: React.lazy(() => import("@/workshop/number-input/number-input")),
        family: ["basic-field", "button", "input"],
        files: ["src/workshop/number-input/index.tsx", "src/workshop/number-input/number-input.tsx"],
    },
    "page-header": {
        name: "PageHeader",
        component: React.lazy(() => import("@/workshop/page-header/page-header")),
        family: [],
        files: ["src/workshop/page-header/index.tsx", "src/workshop/page-header/page-header.tsx"],
    },
    "pagination": {
        name: "Pagination",
        component: React.lazy(() => import("@/workshop/pagination/pagination")),
        family: [],
        files: ["src/workshop/pagination/index.tsx", "src/workshop/pagination/pagination.tsx"],
    },
    "phone-input": {
        name: "PhoneInput",
        component: React.lazy(() => import("@/workshop/phone-input/phone-input")),
        family: ["basic-field", "input"],
        files: ["src/workshop/phone-input/index.tsx", "src/workshop/phone-input/phone-input.tsx"],
    },
    "popover": {
        name: "Popover",
        component: React.lazy(() => import("@/workshop/popover/popover")),
        family: [],
        files: ["src/workshop/popover/index.tsx", "src/workshop/popover/popover.tsx"],
    },
    "progress-bar": {
        name: "ProgressBar",
        component: React.lazy(() => import("@/workshop/progress-bar/progress-bar")),
        family: [],
        files: ["src/workshop/progress-bar/index.tsx", "src/workshop/progress-bar/progress-bar.tsx"],
    },
    "radio-group": {
        name: "RadioGroup",
        component: React.lazy(() => import("@/workshop/radio-group/radio-group")),
        family: ["input", "basic-field"],
        files: ["src/workshop/radio-group/index.tsx", "src/workshop/radio-group/radio-group.tsx"],
    },
    "scroll-area": {
        name: "ScrollArea",
        component: React.lazy(() => import("@/workshop/scroll-area/scroll-area")),
        family: [],
        files: ["src/workshop/scroll-area/index.tsx", "src/workshop/scroll-area/scroll-area.tsx"],
    },
    "select": {
        name: "Select",
        component: React.lazy(() => import("@/workshop/select/select")),
        family: ["basic-field", "input"],
        files: ["src/workshop/select/index.tsx", "src/workshop/select/select.tsx"],
    },
    "separator": {
        name: "Separator",
        component: React.lazy(() => import("@/workshop/separator/separator")),
        family: [],
        files: ["src/workshop/separator/index.tsx", "src/workshop/separator/separator.tsx"],
    },
    "simple-dropzone": {
        name: "SimpleDropzone",
        component: React.lazy(() => import("@/workshop/simple-dropzone/simple-dropzone")),
        family: ["basic-field", "button", "input"],
        files: ["src/workshop/simple-dropzone/index.tsx", "src/workshop/simple-dropzone/simple-dropzone.tsx"],
    },
    "skeleton": {
        name: "Skeleton",
        component: React.lazy(() => import("@/workshop/skeleton/skeleton")),
        family: [],
        files: ["src/workshop/skeleton/index.tsx", "src/workshop/skeleton/skeleton.tsx"],
    },
    "stats": {
        name: "Stats",
        component: React.lazy(() => import("@/workshop/stats/stats")),
        family: [],
        files: ["src/workshop/stats/index.tsx", "src/workshop/stats/stats.tsx"],
    },
    "switch": {
        name: "Switch",
        component: React.lazy(() => import("@/workshop/switch/switch")),
        family: ["basic-field", "input"],
        files: ["src/workshop/switch/index.tsx", "src/workshop/switch/switch.tsx"],
    },
    "table": {
        name: "Table",
        component: React.lazy(() => import("@/workshop/table/table")),
        family: [],
        files: ["src/workshop/table/index.tsx", "src/workshop/table/table.tsx"],
    },
    "tabs": {
        name: "Tabs",
        component: React.lazy(() => import("@/workshop/tabs/tabs")),
        family: [],
        files: ["src/workshop/tabs/index.tsx", "src/workshop/tabs/static-tabs.tsx", "src/workshop/tabs/tabs.tsx"],
    },
    "text-input": {
        name: "TextInput",
        component: React.lazy(() => import("@/workshop/text-input/text-input")),
        family: ["basic-field", "input"],
        files: ["src/workshop/text-input/index.tsx", "src/workshop/text-input/text-input.tsx"],
    },
    "textarea": {
        name: "Textarea",
        component: React.lazy(() => import("@/workshop/textarea/textarea")),
        family: ["basic-field", "input"],
        files: ["src/workshop/textarea/index.tsx", "src/workshop/textarea/textarea.tsx"],
    },
    "timeline": {
        name: "Timeline",
        component: React.lazy(() => import("@/workshop/timeline/timeline")),
        family: [],
        files: ["src/workshop/timeline/index.tsx", "src/workshop/timeline/timeline.tsx"],
    },
    "toaster": {
        name: "Toaster",
        component: React.lazy(() => import("@/workshop/toaster/toaster")),
        family: [],
        files: ["src/workshop/toaster/index.tsx", "src/workshop/toaster/toaster.tsx"],
    },
    "tooltip": {
        name: "Tooltip",
        component: React.lazy(() => import("@/workshop/tooltip/tooltip")),
        family: [],
        files: ["src/workshop/tooltip/index.tsx", "src/workshop/tooltip/tooltip.tsx"],
    },
    "vertical-menu": {
        name: "VerticalMenu",
        component: React.lazy(() => import("@/workshop/vertical-menu/vertical-menu")),
        family: ["disclosure"],
        files: ["src/workshop/vertical-menu/index.tsx", "src/workshop/vertical-menu/vertical-menu.tsx"],
    },
    "button-demo": {
        name: "button-demo",
        component: React.lazy(() => import("@/demo/button-demo")),
        family: [],
        files: ["src/demo/button-demo.tsx"],
    },
    "datagrid-demo": {
        name: "datagrid-demo",
        component: React.lazy(() => import("@/demo/datagrid/datagrid-demo")),
        family: [],
        files: ["src/demo/datagrid/datagrid-demo.tsx"],
    },
    "datagrid-editing-server-side-validation-demo": {
        name: "datagrid-editing-server-side-validation-demo",
        component: React.lazy(() => import("@/demo/datagrid/datagrid-editing-server-side-validation-demo")),
        family: [],
        files: ["src/demo/datagrid/datagrid-editing-server-side-validation-demo.tsx"],
    },
    "datagrid-server-side-demo": {
        name: "datagrid-server-side-demo",
        component: React.lazy(() => import("@/demo/datagrid/datagrid-server-side-demo")),
        family: [],
        files: ["src/demo/datagrid/datagrid-server-side-demo.tsx"],
    },
}
