import "./globals.css"
import { Inter } from "next/font/google"
import { ClientProviders } from "../components/ClientProviders"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

export default function RootLayout({
   children,
}: {
   children: React.ReactNode
}) {
   return (
      <html suppressHydrationWarning={true}>
      <body className={inter.className}>
      <ClientProviders>
         {children}
      </ClientProviders>
      </body>
      </html>
   )
}
