import { ClientProviders } from "@/components/client-providers"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../styles/globals.css"
import React from "react"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={inter.className} suppressHydrationWarning>
        <ClientProviders>
            {children}
        </ClientProviders>
        </body>
        </html>
    )
}

